<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <?php echo $this->headTitle(' - Ramazan İmsakiyesi'); ?>
    <meta name="keyword" value="ramazan, imsakiye, oruç" />
    <meta name="description" value="Bu site Ramazan ayında müslümanların namaz vakitleri bilgisine kolayca erişebilmesi için hazırlanmıştır."

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="<?php echo $this->baseUrl('/img/icon.png'); ?>" />

    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.css" />
    <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js"></script>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-33554183-1']);
        _gaq.push(['_setDomainName', 'imsakiye.mobi']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
</head>
<body>
<?php
echo $this->layout()->content;
?>
</body>
</html>